fastlane_version '2.35.0'

default_platform :ios

platform :ios do
  desc 'Install dependencies'
  lane :pods do
    cocoapods(podfile: 'project/Podfile', use_bundle_exec: true)
  end

  desc 'Runs Illithid tests'
  lane :test do |options|
    scan(workspace: 'project/Illithid.xcworkspace', scheme: 'Illithid_Tests',
      code_coverage: true, output_directory: 'build/reports/tests')
    # Slather not currently working
    # slather(workspace: 'project/Illithid.xcworkspace', proj: 'project/Pods/Pods.xcodeproj', scheme: 'Illithid-Unit-Tests',
    #   binary_basename: 'Illithid', source_directory: 'Illithid/classes', output_directory: 'build/reports/coverage',
    #   simple_output: options[:show_coverage] != true, html: options[:show_coverage] == true, show: options[:show_coverage] == true,
    #   use_bundle_exec: true)
  end

  desc 'Publish new version of Illithid to spec repository'
  lane :publish do
    pod_push(path: 'Illithid.podspec', repo: 'wuakitv', allow_warnings: true)
  end
end
